//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.15 at 09:45:22 PM CEST 
//


package com.android.schemas.sdk.android.repo.repository2.v01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The API level used by the LayoutLib included in a platform to communicate with the IDE.
 *             
 * 
 * <p>Java class for layoutlibType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="layoutlibType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="api" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "layoutlibType")
public class LayoutlibType {

    @XmlAttribute(name = "api", required = true)
    protected int api;

    /**
     * Gets the value of the api property.
     * 
     */
    public int getApi() {
        return api;
    }

    /**
     * Sets the value of the api property.
     * 
     */
    public void setApi(int value) {
        this.api = value;
    }

}
