//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.15 at 09:45:22 PM CEST 
//


package com.android.schemas.sdk.android.repo.repository2.v01;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.android.schemas.repository.android.common.v01.RepositoryType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.android.schemas.sdk.android.repo.repository2._01 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SdkRepository_QNAME = new QName("http://schemas.android.com/sdk/android/repo/repository2/01", "sdk-repository");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.android.schemas.sdk.android.repo.repository2._01
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LayoutlibType }
     * 
     */
    public LayoutlibType createLayoutlibType() {
        return new LayoutlibType();
    }

    /**
     * Create an instance of {@link PlatformDetailsType }
     * 
     */
    public PlatformDetailsType createPlatformDetailsType() {
        return new PlatformDetailsType();
    }

    /**
     * Create an instance of {@link SourceDetailsType }
     * 
     */
    public SourceDetailsType createSourceDetailsType() {
        return new SourceDetailsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RepositoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.android.com/sdk/android/repo/repository2/01", name = "sdk-repository")
    public JAXBElement<RepositoryType> createSdkRepository(RepositoryType value) {
        return new JAXBElement<RepositoryType>(_SdkRepository_QNAME, RepositoryType.class, null, value);
    }

}
