//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.15 at 09:45:22 PM CEST 
//


package com.android.schemas.sdk.android.repo.repository2.v01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.android.schemas.sdk.android.repo.common.v01.ApiDetailsType;


/**
 * 
 *                 type-details subclass for platform components, including information on the
 *                 layoutlib provided.
 *             
 * 
 * <p>Java class for platformDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="platformDetailsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.android.com/sdk/android/repo/common/01}apiDetailsType">
 *       &lt;sequence>
 *         &lt;element name="layoutlib" type="{http://schemas.android.com/sdk/android/repo/repository2/01}layoutlibType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "platformDetailsType", propOrder = {
    "layoutlib"
})
public class PlatformDetailsType
    extends ApiDetailsType
{

    @XmlElement(required = true)
    protected LayoutlibType layoutlib;

    /**
     * Gets the value of the layoutlib property.
     * 
     * @return
     *     possible object is
     *     {@link LayoutlibType }
     *     
     */
    public LayoutlibType getLayoutlib() {
        return layoutlib;
    }

    /**
     * Sets the value of the layoutlib property.
     * 
     * @param value
     *     allowed object is
     *     {@link LayoutlibType }
     *     
     */
    public void setLayoutlib(LayoutlibType value) {
        this.layoutlib = value;
    }

}
