//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.15 at 09:45:22 PM CEST 
//


package com.android.schemas.sdk.android.repo.repository2.v01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import com.android.schemas.sdk.android.repo.common.v01.ApiDetailsType;


/**
 * 
 *                 trivial type-details subclass for source components.
 *             
 * 
 * <p>Java class for sourceDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sourceDetailsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.android.com/sdk/android/repo/common/01}apiDetailsType">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sourceDetailsType")
public class SourceDetailsType
    extends ApiDetailsType
{


}
