//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.19 at 10:21:39 PM CEST 
//


package com.android.schemas.repository.android.sites_common.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.android.schemas.repository.android.sites_common._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SiteList_QNAME = new QName("http://schemas.android.com/repository/android/sites-common/1", "site-list");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.android.schemas.repository.android.sites_common._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SiteListType }
     * 
     */
    public SiteListType createSiteListType() {
        return new SiteListType();
    }

    /**
     * Create an instance of {@link GenericSiteType }
     * 
     */
    public GenericSiteType createGenericSiteType() {
        return new GenericSiteType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SiteListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.android.com/repository/android/sites-common/1", name = "site-list")
    public JAXBElement<SiteListType> createSiteList(SiteListType value) {
        return new JAXBElement<SiteListType>(_SiteList_QNAME, SiteListType.class, null, value);
    }

}
