//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.19 at 10:21:39 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.android.com/repository/android/sites-common/1")
package com.android.schemas.repository.android.sites_common.v1;
