//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.14 at 10:33:00 PM CEST 
//


package com.android.schemas.repository.android.common.v01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *                 A locally-installed package.
 *             
 * 
 * <p>Java class for localPackage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="localPackage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://schemas.android.com/repository/android/common/01}packageFields"/>
 *       &lt;attGroup ref="{http://schemas.android.com/repository/android/common/01}packageAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "localPackage", propOrder = {
    "typeDetails",
    "revision",
    "displayName",
    "usesLicense",
    "dependencies"
})
public class LocalPackage {

    @XmlElement(name = "type-details", required = true)
    protected TypeDetails typeDetails;
    @XmlElement(required = true)
    protected RevisionType revision;
    @XmlElement(name = "display-name", required = true)
    protected String displayName;
    @XmlElement(name = "uses-license")
    protected LicenseRefType usesLicense;
    protected DependenciesType dependencies;
    @XmlAttribute(name = "path", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String path;
    @XmlAttribute(name = "obsolete")
    protected Boolean obsolete;

    /**
     * Gets the value of the typeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TypeDetails }
     *     
     */
    public TypeDetails getTypeDetails() {
        return typeDetails;
    }

    /**
     * Sets the value of the typeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeDetails }
     *     
     */
    public void setTypeDetails(TypeDetails value) {
        this.typeDetails = value;
    }

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link RevisionType }
     *     
     */
    public RevisionType getRevision() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link RevisionType }
     *     
     */
    public void setRevision(RevisionType value) {
        this.revision = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the usesLicense property.
     * 
     * @return
     *     possible object is
     *     {@link LicenseRefType }
     *     
     */
    public LicenseRefType getUsesLicense() {
        return usesLicense;
    }

    /**
     * Sets the value of the usesLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicenseRefType }
     *     
     */
    public void setUsesLicense(LicenseRefType value) {
        this.usesLicense = value;
    }

    /**
     * Gets the value of the dependencies property.
     * 
     * @return
     *     possible object is
     *     {@link DependenciesType }
     *     
     */
    public DependenciesType getDependencies() {
        return dependencies;
    }

    /**
     * Sets the value of the dependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependenciesType }
     *     
     */
    public void setDependencies(DependenciesType value) {
        this.dependencies = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the obsolete property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isObsolete() {
        return obsolete;
    }

    /**
     * Sets the value of the obsolete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setObsolete(Boolean value) {
        this.obsolete = value;
    }

}
