//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.14 at 10:33:00 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.android.com/repository/android/common/01")
package com.android.schemas.repository.android.common.v01;
