//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.15 at 09:45:22 PM CEST 
//


package com.android.schemas.repository.android.generic.v01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import com.android.schemas.repository.android.common.v01.TypeDetails;


/**
 * 
 *                 A trivial implementation of typeDetails, for packages with no type-specific
 *                 information.
 *             
 * 
 * <p>Java class for genericDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="genericDetailsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.android.com/repository/android/common/01}typeDetails">
 *       &lt;all>
 *       &lt;/all>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "genericDetailsType")
public class GenericDetailsType
    extends TypeDetails
{


}
