//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.15 at 09:45:22 PM CEST 
//


package com.android.schemas.repository.android.generic.v01;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.android.schemas.repository.android.common.v01.RepositoryType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.android.schemas.repository.android.generic._01 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Repository_QNAME = new QName("http://schemas.android.com/repository/android/generic/01", "repository");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.android.schemas.repository.android.generic._01
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GenericDetailsType }
     * 
     */
    public GenericDetailsType createGenericDetailsType() {
        return new GenericDetailsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RepositoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.android.com/repository/android/generic/01", name = "repository")
    public JAXBElement<RepositoryType> createRepository(RepositoryType value) {
        return new JAXBElement<RepositoryType>(_Repository_QNAME, RepositoryType.class, null, value);
    }

}
