//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.19 at 10:28:29 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.android.com/sdk/android/repo/sys-img2/01")
package com.android.schemas.sdk.android.repo.sys_img2._01;
