//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.19 at 10:28:29 PM CEST 
//


package com.android.schemas.sdk.android.repo.sys_img2._01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.android.schemas.sdk.android.repo.common.v01.ApiDetailsType;
import com.android.schemas.sdk.android.repo.common.v01.IdDisplayType;


/**
 * 
 *                 type-details subclass including system image-specific information:
 *                 - tag, specifying the device type (tablet, tv, wear, etc.)
 *                 - vendor, the vendor for this system image (android, google, etc.)
 *                 - abi, the architecture for this image (x86, armeabi-v7a, etc.)
 *             
 * 
 * <p>Java class for sysImgDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sysImgDetailsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.android.com/sdk/android/repo/common/01}apiDetailsType">
 *       &lt;sequence>
 *         &lt;element name="tag" type="{http://schemas.android.com/sdk/android/repo/common/01}idDisplayType"/>
 *         &lt;element name="vendor" type="{http://schemas.android.com/sdk/android/repo/common/01}idDisplayType" minOccurs="0"/>
 *         &lt;element name="abi" type="{http://schemas.android.com/sdk/android/repo/sys-img2/01}abiType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sysImgDetailsType", propOrder = {
    "tag",
    "vendor",
    "abi"
})
public class SysImgDetailsType
    extends ApiDetailsType
{

    @XmlElement(required = true)
    protected IdDisplayType tag;
    protected IdDisplayType vendor;
    @XmlElement(required = true)
    protected String abi;

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link IdDisplayType }
     *     
     */
    public IdDisplayType getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdDisplayType }
     *     
     */
    public void setTag(IdDisplayType value) {
        this.tag = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link IdDisplayType }
     *     
     */
    public IdDisplayType getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdDisplayType }
     *     
     */
    public void setVendor(IdDisplayType value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the abi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbi() {
        return abi;
    }

    /**
     * Sets the value of the abi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbi(String value) {
        this.abi = value;
    }

}
