//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.15 at 09:45:22 PM CEST 
//


package com.android.schemas.sdk.android.repo.common.v01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import com.android.schemas.repository.android.common.v01.TypeDetails;
import com.android.schemas.sdk.android.repo.repository2.v01.PlatformDetailsType;
import com.android.schemas.sdk.android.repo.repository2.v01.SourceDetailsType;


/**
 * 
 *                 Abstract subclass of type-details adding elements to specify the android version
 *                 a package corresponds to.
 *             
 * 
 * <p>Java class for apiDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="apiDetailsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.android.com/repository/android/common/01}typeDetails">
 *       &lt;sequence>
 *         &lt;element name="api-level" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="codename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "apiDetailsType", propOrder = {
    "apiLevel",
    "codename"
})
@XmlSeeAlso({
    PlatformDetailsType.class,
    SourceDetailsType.class
})
public abstract class ApiDetailsType
    extends TypeDetails
{

    @XmlElement(name = "api-level")
    protected int apiLevel;
    protected String codename;

    /**
     * Gets the value of the apiLevel property.
     * 
     */
    public int getApiLevel() {
        return apiLevel;
    }

    /**
     * Sets the value of the apiLevel property.
     * 
     */
    public void setApiLevel(int value) {
        this.apiLevel = value;
    }

    /**
     * Gets the value of the codename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodename() {
        return codename;
    }

    /**
     * Sets the value of the codename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodename(String value) {
        this.codename = value;
    }

}
